<?php

use Atlas\Core\Blocks\BaseBlock;

return [
    /*
    |--------------------------------------------------------------------------
    | Menus
    |--------------------------------------------------------------------------
    |
    | All menus that should be registered
    |
    */
    'menus' => [
        'header-top' => 'Header - Top',
        'header-main' => 'Header - Main',
        'footer-top' => 'Footer - Top',
        'footer-main' => 'Footer - Main',
    ],

    /*
    |--------------------------------------------------------------------------
    | Allowed core blocks
    |--------------------------------------------------------------------------
    |
    | All allowed core WordPress blocks should be entered here
    |
     */
    'blocks' => [
        'allowed' => [
            'core/block',
            'core/paragraph',
            'core/list',
            'core/heading',
            'core/quote',
            'core/spacer',
            'core/columns',
            'core/image',
            'core/embed'
        ],
        'categories' => [
            [
                'slug' => BaseBlock::CATEGORY_BEST_PRACTICE,
                'title' => __('Blocks - Best Practice', 'atlas-blocks'),
            ],
            [
                'slug' => BaseBlock::CATEGORY_BEST_PRACTICE_LIKE,
                'title' => __('Blocks - Best Practice Like', 'atlas-blocks'),
            ],
            [
                'slug' => BaseBlock::CATEGORY_CUSTOM,
                'title' => __('Blocks - Custom', 'atlas-blocks'),
            ],
        ]
    ],

    /*
    |--------------------------------------------------------------------------
    | Widgets
    |--------------------------------------------------------------------------
    |
    | All widgets that should be registered
    |
    */
    'widgets' => [
        'sidebar-primary' => 'Primary',
    ],

    /*
    |--------------------------------------------------------------------------
    | Image sizes
    |--------------------------------------------------------------------------
    |
    | All image sizes that should be generated by wordpress
    |
    */
    'remove_image_sizes' => [
        'medium',
        'large',
        '1536x1536',
        '2048x2048',
    ],

    'extra_image_sizes' => [
        'image_size_small' => [
            'width' => 144,
            'height' => 99999,
        ],
        'image_size_medium' => [
            'width' => 240,
            'height' => 99999,
        ],
        'image_size_large' => [
            'width' => 408,
            'height' => 99999,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Theme Support
    |--------------------------------------------------------------------------
    |
    | All image sizes that should be generated by wordpress
    |
    */
    'support' => [
        // Enable features from the Soil plugin if activated. @link https://roots.io/plugins/soil/
        'soil' => [
            'clean-up',
            'nice-search',
            'relative-urls',
        ],
        'title-tag',  // Enable plugins to manage the document title @link https://developer.wordpress.org/reference/functions/add_theme_support/#title-tag
        'post-thumbnails',  // Enable post thumbnails @link https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/
        'responsive-embeds', // Enable responsive embed support @link https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#responsive-embedded-content
        //  Enable HTML5 markup support @link https://developer.wordpress.org/reference/functions/add_theme_support/#html5
        'html5' => [
            'caption',
            'comment-form',
            'comment-list',
            'gallery',
            'search-form',
            'script',
            'style',
        ],
        'customize-selective-refresh-widgets', // Enable selective refresh for widgets in customizer @link https://developer.wordpress.org/themes/advanced-topics/customizer-api/#theme-support-in-sidebars

        'acf-default-blocks', // Adds "Default Blocks" to ACF options page.
        'atlas-reusable-blocks', // Adds "Reusable Blocks" to the admin sidebar
        'atlas-cleanup' // Cleans up the admin backend by removing various metaboxes and adminbar items
    ],

    'remove_support' => [
        'block-templates', // Disable full-site editing support. @link https://wptavern.com/gutenberg-10-5-embeds-pdfs-adds-verse-block-color-options-and-introduces-new-patterns
        'core-block-patterns' // Disable the default block patterns. @link https://developer.wordpress.org/block-editor/developers/themes/theme-support/#disabling-the-default-block-patterns
    ],

    /*
    |--------------------------------------------------------------------------
    | Theme Option Pages
    |--------------------------------------------------------------------------
    |
    | All option pages that are added to the admin menu
    |
    */
    'options_pages' => [
        [
            'page_title' => 'Theme Settings',
            'menu_title' => 'Theme Settings',
            'menu_slug' => 'theme-settings',
            'redirect' => false,
            'autoload' => true,
            'sub_pages' => [
                [
                    'page_title' => __('Code Snippets'),
                    'menu_title' => __('Code Snippets'),
                    'slug' => 'code-snippets',
                    'parent_slug' => 'theme-settings',
                    'autoload' => true
                ]
            ]
        ]
    ]
];
